import { PaymentType, Plan, PLAN_NAME, PLAN_SUBNAME } from '@/app/types';

export const Subscriptions: {
  id: string;
  name: PLAN_NAME;
  subPlans: {
    id: string;
    type: PaymentType;
    planDescriptions: Plan[];
  }[];
}[] = [
  {
    id: 'CREDIT',
    name: PLAN_NAME.CREDIT,
    subPlans: [
      {
        id: PaymentType.MONTHLY,
        type: PaymentType.MONTHLY,
        planDescriptions: [
          {
            name: PLAN_NAME.CREDIT,
            paymentType: PaymentType.MONTHLY,
            planDescription: [
              {
                planTitle: PLAN_SUBNAME.FREE_FOREVER,
                price: '0€/Month',
                CTO: 'Get 15-60% OFF with Upgrade',
                CTODescription: 'Upgrade to Paid Plan to Get this Offer.',
                credit: '1000',
                subscribedUsers: '',
                planPoint: [
                  '500 Credits',
                  '10 content/posts per month (ad copy)',
                  'Limited access to prompt templates',
                  'Basic AI features',
                  '5 Competitor analysis',
                  '3 languages localisation',
                  '10X content revisions',
                  'Publish/Promote to 3 channels (Highlight all possible marketing channels)',
                  '1 Brand',
                  'simplecx watermark',
                  '1 team member',
                  'No Voice-over (video)',
                  'Words-15K/month',
                  'Assets with no premium features',
                ],
              },
              {
                planTitle: PLAN_SUBNAME.UNIQUE,
                price: '€49.99/Month',
                CTO: 'Get 15-60% OFF with Early Signup',
                CTODescription: 'For the First 3 Months',
                credit: '5000',
                subscribedUsers: '',
                planPoint: [
                  '5000 Credits',
                  '50 contents/posts',
                  'Limited access to premium prompt templates',
                  '10+ AI features',
                  '10 competitor analysis',
                  'Basic analytical tool (Keyword, phrases & topics)',
                  '100+ projects',
                  '24/7 support',
                  '5 languages localisation',
                  '100X content revisions',
                  'Content optimisation',
                  'Publish/Promote to 10 channels (Highlight all possible marketing channels)',
                  '3 Brands',
                  '3 team members',
                  '60 Voice-over minutes (video)',
                  'Words-25K/month',
                  'Trends and content recommendations',
                  '10K+ premium features and assets',
                ],
                additionalFeatures: [
                  'API Access',
                  'Freelance Partner Access: VEE',
                  'Channel Integration',
                ],
              },
              {
                planTitle: PLAN_SUBNAME.UNICORN,
                price: '€99.99/Month',
                CTO: 'Get 15-60% OFF with Early Signup',
                CTODescription: 'For the First 6 Months',
                credit: '10000',
                subscribedUsers: '',
                planPoint: [
                  '10000 Credits',
                  '100 contents/posts',
                  'Limited access to industry-specific premium prompt template',
                  '25+ AI features',
                  '20 competitor analysis',
                  'Advanced analytic tools (keywords, phrases & topics)',
                  'Multiple projects',
                  'Priority support',
                  '10 languages localisation',
                  '1000X content revision',
                  'Content optimisation',
                  'Publish/Promote to 20 channels (Highlight all possible marketing channels)',
                  'Up to 5 brands',
                  '10 team members',
                ],
                additionalFeatures: [
                  'API Access',
                  'Freelance Partner Access: VEE',
                  'Channel Integration',
                ],
              },
              {
                planTitle: PLAN_SUBNAME.CUSTOM,
                price: 'Contact Sales',
                CTO: 'Get 15-60% OFF with Early Signup',
                CTODescription: 'For the First 13 Months',
                credit: 'Unlimited Credits',
                subscribedUsers: '',
                planPoint: [
                  'Unlimited Credits',
                  'Unlimited content/post',
                  'Unlimited access to industry-specific premium prompt templates',
                  'AI model tailored to brand voice',
                  'Unlimited competitor analysis',
                  'API access for importing and exporting in bulk',
                  'Multiple projects',
                  'Dedicated account manager',
                  'Multiple language localisation',
                  'Unlimited content revisions',
                  'Content optimisation',
                  'Publish/Promote to unlimited channels (Highlight all possible marketing channels)',
                  'Unlimited brands',
                  'Unlimited team members',
                ],
                additionalFeatures: [
                  'API Access',
                  'Freelance Partner Access: VEE',
                  'Channel Integration',
                ],
              },
            ],
          },
        ],
      },
      {
        id: PaymentType.ANNUALY,
        type: PaymentType.ANNUALY,
        planDescriptions: [
          {
            name: PLAN_NAME.CREDIT,
            paymentType: PaymentType.MONTHLY,
            planDescription: [
              {
                planTitle: PLAN_SUBNAME.FREE_FOREVER,
                price: '0€/Month',
                CTO: 'Start Creating- FP or AI',
                CTODescription: 'Upgrade to a Paid Plan to get this offer.',
                credit: '1000',
                subscribedUsers: '',
                planPoint: [
                  '10 content/posts per month (ad copy)',
                  'Limited access to prompt templates',
                  'Basic AI features',
                  '5 Competitor analysis',
                  '3 languages localisation',
                  '10X content revisions',
                  'Publish/Promote to 3 channels (Highlight all possible marketing channels)',
                  '1 Brand',
                  'simplecx watermark',
                  '1 team member',
                  'No Voice-over (video)',
                  'Words-15K/month',
                  'Assets with no premium features',
                ],
              },
              {
                planTitle: PLAN_SUBNAME.UNIQUE,
                price: '€49.99/Month',
                CTO: 'Start Creating - FP or AI',
                CTODescription: 'For the First 3 Months',
                credit: '5000',
                subscribedUsers: '',
                planPoint: [
                  '50 contents/posts',
                  'Limited access to premium prompt templates',
                  '10+ AI features',
                  '10 competitor analysis',
                  'Basic analytical tool (Keyword, phrases & topics)',
                  '100+ projects',
                  '24/7 support',
                  '5 languages localisation',
                  '100X content revisions',
                  'Content optimisation',
                  'Publish/Promote to 10 channels (Highlight all possible marketing channels)',
                  '3 Brands',
                  '3 team members',
                  '60 Voice-over minutes (video)',
                  'Words-25K/month',
                  'Trends and content recommendations',
                  '10K+ premium features and assets',
                ],
                additionalFeatures: [
                  'API Access',
                  'Freelance Partner Access: VEE',
                  'Channel Integration',
                ],
              },
              {
                planTitle: PLAN_SUBNAME.UNICORN,
                price: '€99.99/Month',
                CTO: 'Start Creating - FP or AI',
                CTODescription: 'For the First 3 Months',
                credit: '10000',
                subscribedUsers: '',
                planPoint: [
                  '100 contents/posts',
                  'Limited access to industry-specific premium prompt template',
                  '25+ AI features',
                  '20 competitor analysis',
                  'Advanced analytic tools (keywords, phrases & topics)',
                  'Multiple projects',
                  'Priority support',
                  '10 languages localisation',
                  '1000X content revision',
                  'Content optimisation',
                  'Publish/Promote to 20 channels (Highlight all possible marketing channels)',
                  'Up to 5 brands',
                  '10 team members',
                ],
                additionalFeatures: [
                  'API Access',
                  'Freelance Partner Access: VEE',
                  'Channel Integration',
                ],
              },
              {
                planTitle: PLAN_SUBNAME.CUSTOM,
                price: 'Contact Sales',
                CTO: 'Start Creating - FP or AI',
                CTODescription: 'For the First 3 Months',
                credit: 'Unlimited Credits',
                subscribedUsers: '',
                planPoint: [
                  'Unlimited content/post',
                  'Unlimited access to industry-specific premium prompt templates',
                  'AI model tailored to brand voice',
                  'Unlimited competitor analysis',
                  'API access for importing and exporting in bulk',
                  'Multiple projects',
                  'Dedicated account manager',
                  'Multiple language localisation',
                  'Unlimited content revisions',
                  'Content optimisation',
                  'Publish/Promote to unlimited channels (Highlight all possible marketing channels)',
                  'Unlimited brands',
                  'Unlimited team members',
                ],
                additionalFeatures: [
                  'API Access',
                  'Freelance Partner Access: VEE',
                  'Channel Integration',
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'BUNDLE',
    name: PLAN_NAME.BUNDLE,
    subPlans: [
      {
        id: 'BUNDLE_MONTHLY',
        type: PaymentType.MONTHLY,
        planDescriptions: [
          {
            name: PLAN_NAME.BUNDLE,
            paymentType: PaymentType.MONTHLY,
            planDescription: [
              {
                planTitle: PLAN_SUBNAME.FREE_FOREVER,
                price: '0€/Month',
                CTO: 'Start Creating',
                CTODescription: '',
                planPoint: [
                  'Access to 1 Freelance Partner (FP) Create 1 content format only. (Unlimited content for video, image, text copy, audio, or icons)',
                ],
                subscribedUsers: '',
              },
              {
                planTitle: PLAN_SUBNAME.UNIQUE,
                price: '€29.49/Month',
                CTO: 'Start Creating',
                CTODescription: '',
                planPoint: [
                  'Create 2 content formats. (Unlimited content for video, image, text copy, audio, or icons)',
                ],
                subscribedUsers: '',
              },
              {
                planTitle: PLAN_SUBNAME.UNICORN,
                price: '€44.49/Month',
                CTO: 'Start Creating',
                CTODescription: '',
                planPoint: [
                  'Access to limited AI tools/features',
                  'Access to 3 Freelance Partners (FPs)',
                  'Create 5 content formats (Unlimited content for video, image, text copy, audio, or icons)',
                ],
                subscribedUsers: '',
              },
              {
                planTitle: PLAN_SUBNAME.SUPER_QUNICORN,
                price: '€179.49/Month',
                CTO: 'Start Creating',
                CTODescription: '',
                planPoint: [
                  'Create unlimited content (any format or type)',
                  'Access to unlimited Freelancers Partners (FPs)',
                ],
                subscribedUsers: '',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'DYNAMIC',
    name: PLAN_NAME.DYNAMIC,
    subPlans: [
      {
        id: 'DYNAMIC',
        type: PaymentType.MONTHLY,
        planDescriptions: [
          {
            name: PLAN_NAME.DYNAMIC,
            paymentType: PaymentType.MONTHLY,
            planDescription: [
              {
                planTitle: PLAN_SUBNAME.FREE_FOREVER,
                price: '0€/Month',
                CTO: 'Access to limited AI tools/features',
                CTODescription: '',
                planPoint: [
                  'Access to 1 Freelance Partner (FP) Create 1 content format only. (Unlimited content for video, image, text copy, audio, or icons)',
                ],
                subscribedUsers: '',
              },
              {
                planTitle: PLAN_SUBNAME.UNIQUE,
                price: '€29.49/Month',
                CTO: 'Access to limited AI tools/features',
                CTODescription: '',
                planPoint: [
                  'Create 2 content formats. (Unlimited content for video, image, text copy, audio, or icons)',
                ],
                subscribedUsers: '',
              },
              {
                planTitle: PLAN_SUBNAME.UNICORN,
                price: '€44.49/Month',
                CTO: 'Access to unlimited AI tools/features',
                CTODescription: '',
                planPoint: [
                  'Access to 3 Freelance Partners (FPs)',
                  'Create 5 content formats (Unlimited content for video, image, text copy, audio, or icons)',
                ],
                subscribedUsers: '',
              },
              {
                planTitle: PLAN_SUBNAME.SUPER_QUNICORN,
                price: '€179.49/Month',
                CTO: 'Access to unlimited AI tools/features',
                CTODescription: '',
                planPoint: [
                  'Create unlimited content (any format or type)',
                  'Access to unlimited Freelancers Partners (FPs)',
                ],
                subscribedUsers: '',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'FREELANCER',
    name: PLAN_NAME.FREELANCE_PARTNERS,
    subPlans: [
      {
        id: 'FREELANCER_MONTHLY',
        type: PaymentType.MONTHLY,
        planDescriptions: [
          {
            name: PLAN_NAME.FREELANCE_PARTNERS,
            paymentType: PaymentType.MONTHLY,
            planDescription: [
              {
                planTitle: PLAN_SUBNAME.FREE_FOREVER,
                price: '0€/Month',
                CTO: 'Not Mention',
                CTODescription: '',
                planPoint: ['-'],
                subscribedUsers: '',
              },
              {
                planTitle: PLAN_SUBNAME.RPODIGEE,
                price: '€4.99/Month',
                CTO: 'Access to limited AI tools/features',
                CTODescription: '',
                planPoint: [
                  'Up to 50 gigs monthly',
                  'No extra gigs',
                  'Consistent daily appearance to customers and prioritised front page',
                ],
                subscribedUsers: '',
              },
              {
                planTitle: PLAN_SUBNAME.PRO,
                price: '€8.49/Month',
                CTO: 'Access to unlimited AI tools/features',
                CTODescription: '',
                planPoint: [
                  'Up to 100 gigs monthly',
                  'Extra gigs from credit subscribers on demand',
                  'Medium priority and constant suggestions to customers',
                ],
                subscribedUsers: '',
              },
              {
                planTitle: PLAN_SUBNAME.OG,
                price: '€14.49/Month',
                CTO: 'Access to unlimited AI tools/features',
                CTODescription: '',
                planPoint: [
                  'Unlimited gigs',
                  'Extra gigs from express customers',
                  'Priority and constant suggestions to customers',
                ],
                subscribedUsers: '',
              },
            ],
          },
        ],
      },
    ],
  },
];
