import type { TabId } from "./tabData";

export interface PricingPlan {
	title: string;
	price: string;
	features: string[];
	button: string;
	buttonNextText?: string; // Additional text below the button
	badge?: string;
	planType: string;
}

export const pricingData: Record<
	TabId,
	{ monthlyPlans: PricingPlan[]; yearlyPlans: PricingPlan[] }
> = {
	dynamic: {
		monthlyPlans: [
			{
				title: "Free Forever",
				price: "0€/Month",
				features: [
					"Access to limited AI tools/features",
					"Create 1 content format only (Unlimited content for video, image, text copy, audio, or icons)",
				],
				button: "Get 15-60% OFF with Upgrade",
				buttonNextText: "Upgrade to a Paid Plan to get this offer",
				planType: "dynamicFree",
			},
			{
				title: "Starter",
				price: "€19.99/Month",
				features: ["300 credits per month", "Basic AI tools"],
				button: "Get 10% OFF with Early Signup",
				buttonNextText: "For the First 3 Months",
				badge: "Popular",
				planType: "dynamicMonthlyStarter",
			},
			{
				title: "Pro",
				price: "€49.99/Month",
				features: ["1000 credits per month", "Advanced AI tools"],
				button: "Get 20% OFF with Early Signup",
				buttonNextText: "For the First 6 Months",
				planType: "dynamicMonthlyPro",
			},
		],
		yearlyPlans: [
			{
				title: "Free Forever",
				price: "0€/Year",
				features: [
					"Access to limited AI tools/features",
					"Create 1 content format only (Unlimited content for video, image, text copy, audio, or icons)",
				],
				button: "Get Started",
				buttonNextText: "Upgrade to a Paid Plan to get this offer",
				planType: "dynamicFree",

			},
			{
				title: "Starter",
				price: "€15.99/Month (Billed Annually)",
				features: ["300 credits per month", "Basic AI tools"],
				button: "Get 15% OFF with Upgrade",
				buttonNextText: "For the First 3 Months",
				badge: "Popular",
				planType: "dynamicYearlyStarter",
			},
			{
				title: "Pro",
				price: "€39.99/Month (Billed Annually)",
				features: ["1000 credits per month", "Advanced AI tools"],
				button: "Get 25% OFF with Upgrade",
				buttonNextText: "For the First 6 Months",
				planType: "dynamicYearlyPro",
			},
		],
	},
	bundle: {
		monthlyPlans: [
			{
				title: "Free Forever",
				price: "0€/Month",
				features: [
					"Access to limited AI tools/features",
					"X",
					"Create 1 content format only. (Unlimited content for video, image, text copy, audio, or icons)",
				],
				button: "Get 15-60% OFF when you upgrade to a paid plan at launch",
				buttonNextText: "For the First 3-13 Months",
				planType: "bundleFree",
			},
			{
				title: "Unique",
				price: "29.49€/Month",
				features: [
					"Access to limited AI tools/features",
					"Access to 1 Freelance Partner (FP)",
					"Create 2 content formats. (Unlimited content for video, image, text copy, audio, or icons)",
				],
				button: "Get 15% OFF with Early Signup",
				badge: "Popular",
				buttonNextText: "For the First 3 Months",
				planType: "bundleMonthlyUnicorn",
			},
			{
				title: "Unicorn",
				price: "44.49€/Month",
				features: [
					"Access to unlimited AI tools/features",
					"Access to 3 Freelance Partners (FPs)",
					"Create 5 content formats. (Unlimited content for video, image, text copy, audio, or icons)",
				],
				button: "Get 25% OFF with Early Signup",
				buttonNextText: "For the First 6 Months",
				planType: "bundleMonthlyUnicorn",
			},
			{
				title: "Super Unicorn",
				price: "179.49€/Month",
				features: [
					"Access to unlimited AI tools/features",
					"Access to unlimited Freelance Partners (FPs)",
					"Create unlimited content (any format or type)",
				],
				button: "Get 60% OFF with Early Signup",
				buttonNextText: "For the First 13 Months",
				planType: "bundleMonthlySuperUnicorn",

			},
		],
		yearlyPlans: [
			{
				title: "Free Forever",
				price: "0€/Year",
				features: [
					"Access to limited AI tools/features",
					"Access to 1 Freelance Partner (FP)",
					"Create 2 content formats. (Unlimited content for video, image, text copy, audio, or icons)",
				],
				button: "Get Started",
				buttonNextText: "Upgrade to a Paid Plan to get this offer",
				planType: "bundleFree",
			},
			{
				title: "Unique",
				price: "23.59€/Month (Billed Annually)",
				features: [
					"Access to unlimited AI tools/features",
					"Access to 3 Freelance Partners (FPs)",
					"Create 5 content formats. (Unlimited content for video, image, text copy, audio, or icons)",
				],
				badge: "Popular",
				button: "Get 20% OFF with Upgrade",
				buttonNextText: "For the First 3 Months",
				planType: "bundleYearlyUnicorn",
			},
			{
				title: "Super Unicorn",
				price: "143.59€/Month (Billed Annually)",
				features: [
					"Access to unlimited AI tools/features",
					"Access to unlimited Freelance Partners (FPs)",
					"Create unlimited content (any format or type)",
				],
				button: "Get 30% OFF with Upgrade",
				buttonNextText: "For the First 13 Months",
				planType: "bundleYearlySuperUnicorn",
			},
		],
	},
	credit: {
		monthlyPlans: [
			{
				title: "Free Forever",
				price: "0€/Month",
				features: [
					"1,000 credits",
					"10 content/posts per month (ad copy)",
					"Limited access to prompt templates",
					"Basic AI features",
					"5 Competitor analysis",
					"X",
					"X",
					"3 languages localisation",
					"10X content revisions",
					"X",
					"Publish/Promote to 3 channels (Highlight all possible marketing channels)",
					"1 Brand",
					"Simplex watermark",
					"1 team member",
					"No Voice-over (video)",
					"Words-15K/month",
					"Assets with no premium features",
				],
				button: "Get 15-60% OFF when you upgrade to a paid plan at launch",
				buttonNextText: "For the First 3-13 Months",
				planType: "creditFree",
			},
			{
				title: "Unique",
				price: "49.99€/Month",
				features: [
					"5,000 credits",
					"50 contents/posts",
					"Limited access to premium prompt templates",
					"10+ AI features",
					"10 competitor analysis",
					"Basic analytical tool (Keyword, phrases & topics)",
					"100+ projects",
					" 24/7 support",
					"5 languages localisation",
					"100X  content revisions",
					"Content optimisation",
					"Publish/Promote to 10 channels (Highlight all possible marketing channels)",					
					"3 Brands",
					"X",
					"3 team members",
					"60 Voice-over minutes (video)",
					"Words-25K/month",
					"Trends and content recommendations",
					"10K+ premium features and assets",					
				],
				button: "Get 15% OFF with Early Signup",
				badge: "Popular",
				buttonNextText: "For the First 3 Months",
				planType: "creditMonthlyUnique",
			},
			{
				title: "Unicorn",
				price: "99.99€/Month",
				features: [
					"10,000 credits",
					"100 contents/posts",
					"Limited access to industry-specific premium prompt templates",
					"25+ AI features",
					"20 competitor analysis",
					"Advanced analytic tools (keywords, phrases & topics)",
					"Multiple projects",
					"Priority support",
					"10 languages localisation",
					"1000X content revision",
					"Content optimisation",
					"Publish/Promote to 20 channels (Highlight all possible marketing channels)",
					"Up to 5 brands",
					"X",
					"10 team members",
					"120 Voice-over minutes (video)",
					"Words-50K/month",
					"Limited trends and content recommendations",
					"100K+ premium features and assets",
				],
				button: "Get 25% OFF with Early Signup",
				buttonNextText: "For the First 6 Months",
				planType: "creditMonthlyUnicorn",
			},
			{
				title: "Custom",
				price: "Contact Sales",
				features: [
					"Unlimited credits",
					"Unlimited content/post",
					"Unlimited access to industry-specific premium prompt templates",
					"AI model tailored to brand voice",
					"Unlimited competitor analysis",
					"API access for importing and exporting in bulk",
					"Multiple projects",
					"Dedicated account manager",
					"Multiple language localisation",
					"Unlimited content revisions",
					"Content optimisation",
					"Publish/Promote to unlimited channels (Highlight all possible marketing channels)",
					"Unlimited brands",
					"X",
					"Unlimited team members",
					"360 Voice-over minutes (video)",
					"Words-250K/month",
					"Unlimited trends and content recommendations",
					"1M+ premium features and assets",
				],
				button: "Get Up to 60% OFF with Early Signup",
				buttonNextText: "For the First 13 Months",
				planType: "creditMonthlyCustom",
			},
		],
		yearlyPlans: [
			{
				title: "Free Forever",
				price: "0€/Year",
				features: [
					"1,000 credits",
					"10 content/posts per month (ad copy)",
					"Limited access to prompt templates",
					"Basic AI features",
					"5 Competitor analysis",
					"X",
					"X",
					"3 languages localisation",
					"10X content revisions",
					"X",
					"Publish/Promote to 3 channels (Highlight all possible marketing channels)",
					"1 Brand",
					"Simplex watermark",
					"1 team member",
					"No Voice-over (video)",
					"Words-15K/month",
					"Assets with no premium features",
				],
				button: "Get Started",
				buttonNextText: "Upgrade to a Paid Plan to get this offer",
				planType: "creditFree",
			},
			{
				title: "Unique",
				price: "39.99€/Month (Billed Annually)",
				features: [
					"5,000 credits",
					"50 contents/posts",
					"Limited access to premium prompt templates",
					"10+ AI features",
					"10 competitor analysis",
					"Basic analytical tool (Keyword, phrases & topics)",
					"100+ projects",
					" 24/7 support",
					"5 languages localisation",
					"100X  content revisions",
					"Content optimisation",
					"Publish/Promote to 10 channels (Highlight all possible marketing channels)",					
					"3 Brands",
					"X",
					"3 team members",
					"60 Voice-over minutes (video)",
					"Words-25K/month",
					"Trends and content recommendations",
					"10K+ premium features and assets",	
				],
				badge: "Popular",
				button: "Get 20% OFF with Upgrade",
				buttonNextText: "For the First 3 Months",
				planType: "creditYearlyUnique",
			},
			{
				title: "Unicorn",
				price: "79.99€/Month (Billed Annually)",
				features: [
					"Access to limited AI tools/features",
					"10,000 credits",
					"100 contents/posts",
					"Limited access to industry-specific premium prompt templates",
					"25+ AI features",
					"20 competitor analysis",
					"Advanced analytic tools (keywords, phrases & topics)",
					"Multiple projects",
					"Priority support",
					"10 languages localisation",
					"1000X content revision",
					"Content optimisation",
					"Publish/Promote to 20 channels (Highlight all possible marketing channels)",
					"Up to 5 brands",
					"X",
					"10 team members",
					"120 Voice-over minutes (video)",
					"Words-50K/month",
					"Limited trends and content recommendations",
					"100K+ premium features and assets",
				],
				button: "Get 30% OFF with Upgrade",
				buttonNextText: "For the First 6 Months",
				planType: "creditYearlyUnicorn",
			},
		],
	},
	freelance: {
		monthlyPlans: [
			{
				title: "Freelance Starter",
				price: "€19.99/Month",
				features: [
					"200 credits per month",
					"Access to basic AI tools",
					"Collaboration tools for teams",
				],
				button: "Get 15% OFF with Upgrade",
				buttonNextText: "For the First 3 Months",
				badge: "Popular",
				planType: "freelanceFree",
			},
			{
				title: "Freelance Pro",
				price: "€49.99/Month",
				features: [
					"500 credits per month",
					"Access to advanced AI tools",
					"Priority support",
				],
				button: "Get 20% OFF with Upgrade",
				buttonNextText: "For the First 3 Months",
				planType: "freelanceMonthlyPro",
			},
		],
		yearlyPlans: [
			{
				title: "Freelance Starter",
				price: "€15.99/Month (Billed Annually)",
				features: [
					"200 credits per month",
					"Access to basic AI tools",
					"Collaboration tools for teams",
				],
				button: "Get 20% OFF with Upgrade",
				buttonNextText: "For the First 3 Months",
				badge: "Popular",
				planType: "freelanceYearlyStarter",
			},
			{
				title: "Freelance Pro",
				price: "€39.99/Month (Billed Annually)",
				features: [
					"500 credits per month",
					"Access to advanced AI tools",
					"Priority support",
				],
				button: "Get 25% OFF with Upgrade",
				buttonNextText: "For the First 3 Months",
				planType: "freelanceYearlyPro",
			},
		],
	},
};